services:
  - type: web
    name: cartomante-ai
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: google-credentials.json
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
